// platform-react/src/App.tsx
import './App.css'
import { Outlet } from 'react-router-dom'
import Header from './components/Header'
import Footer from './components/Footer'
import ChatWidget from './components/ChatWidget/ChatWidget'

function App() {
  return (
    <>
      <Header />
      <Outlet />
      <Footer />
      <ChatWidget />
    </>
  )
}

export default App

// platform/src/App.vue
<script setup>
import { ref } from "vue";
import Header from "./components/Header.vue";
import Footer from "./components/Footer.vue";
import ChatWidget from "./components/ChatWidget.vue";

const headerRef = ref(null);

const handleShowLoginModal = () => {
  if (headerRef.value) {
    headerRef.value.openLoginModal();
  }
};
</script>

<template>
  <div>
    <Header ref="headerRef" />
    <router-view @showLoginModal="handleShowLoginModal" />
    <Footer />
    <ChatWidget />
  </div>
</template>

<style scoped>
.app-container {
  max-width: var(--app-width) !important;
  width: 100%;
}
</style>
