// platform-react/src/components/InfoComponent/InfoComponent.tsx
import React, { useEffect } from 'react';
import SingleInfo from './SingleInfo';
import { useInformations } from '../../hooks/useInformations';
import './InfoComponent.css';

const InfoComponent: React.FC = () => {
  const { isLoadingInformationsList, getInformationsList, informationsList } = useInformations();

  useEffect(() => {
    getInformationsList();
  }, []);

  if (isLoadingInformationsList) {
    return (
      <div className="info-component-loading">
        <div className="spinner-border text-primary" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="d-flex flex-column gap-3">
      {informationsList?.map((info, index) => (
        <SingleInfo
          key={index}
          title={info.title}
          description={info.content}
        />
      ))}
    </div>
  );
};

export default InfoComponent;

// platform/src/components/InfoComponent/InfoComponent.vue
<script setup>
import { onMounted } from "vue";
import SingleInfo from "./SingleInfo.vue";
import { useInformations } from "../../composables/informations";
const { isLoadingInformationsList, getInformationsList, informationsList } =
  useInformations();
onMounted(async () => {
  await getInformationsList();
});
</script>

<template>
  <div
    v-loading="isLoadingInformationsList"
    class="d-flex flex-column gap-3"
  >
    <SingleInfo
      v-for="(info, index) in informationsList"
      :key="index"
      :title="info.title"
      :description="info.content"
    />
  </div>
</template>
