// src/components/OutroComponent.vue
<template>
  <div
    class="position-relative overflow-hidden rounded-3 d-flex align-items-center justify-content-center text-center text-white"
    style="height: 295px; background-color: var(--pink)"
  >
    <img
      src="../assets/outro-image.png"
      alt="volutra car"
      class="position-absolute top-0 start-0 w-100 h-100 d-block z-0"
      style="opacity: 0.2; object-fit: cover; object-position: 78% 74%"
    />

    <span class="position-relative z-1 fw-bold fs-2 px-3">
      Postaw na innowację. Postaw na Aureon.
    </span>
  </div>
</template>

// platform-react/src/components/OutroComponent.tsx
import React from 'react';
import outroImage from '../assets/outro-image.png';
import './OutroComponent.css';

const OutroComponent: React.FC = () => {
  return (
    <div className="outro-component">
      <img
        src={outroImage}
        alt="volutra car"
        className="outro-image"
      />

      <span className="outro-text">
        Postaw na innowację. Postaw na Aureon.
      </span>
    </div>
  );
};

export default OutroComponent;
