// platform-react/src/components/CarRange/CarCustomization.tsx
import React, { useState, useMemo } from 'react';
import ButtonComponent from '../common/ButtonComponent';
import { useSummary } from '../../hooks/useSummary';
import './CarCustomization.css';

interface CarVersion {
  id: number;
  title?: string;
  titile?: string;
  name?: string;
  price: number;
}

interface CarColor {
  id: number;
  name: string;
  value: string;
}

interface CarAdditional {
  id: number;
  title: string;
  price: number;
}

interface Car {
  id: number;
  name: string;
  versions?: CarVersion[];
  colors?: CarColor[];
  additionals?: CarAdditional[];
}

interface CarCustomizationProps {
  car: Car;
  onClose: () => void;
}

const CarCustomization: React.FC<CarCustomizationProps> = ({ car, onClose }) => {
  const { setSelectedCar } = useSummary();

  const [version, setVersion] = useState<number | null>(car.versions?.[0]?.id ?? null);
  const [selectedAddonIds, setSelectedAddonIds] = useState<number[]>([]);
  const [color, setColor] = useState<number | null>(car.colors?.[0]?.id ?? null);

  const basePrice = useMemo(() => {
    const versions = car.versions || [];
    const v = versions.find((x) => x.id === version);
    return Number(v?.price) || 0;
  }, [car.versions, version]);

  const selectedAddons = useMemo(() => {
    const ids = selectedAddonIds.map((id) => Number(id));
    return (car.additionals || []).filter((a) => ids.includes(Number(a.id)));
  }, [car.additionals, selectedAddonIds]);

  const addonsTotal = useMemo(
    () => selectedAddons.reduce((sum, a) => sum + (Number(a.price) || 0), 0),
    [selectedAddons]
  );

  const totalPrice = useMemo(() => basePrice + addonsTotal, [basePrice, addonsTotal]);

  const formatPrice = (value: number) => {
    const n = Number(value ?? 0) || 0;
    return n.toLocaleString('pl-PL');
  };

  const toggleAddon = (addonId: number) => {
    setSelectedAddonIds((prev) =>
      prev.includes(addonId) ? prev.filter((id) => id !== addonId) : [...prev, addonId]
    );
  };

  const saveToSummary = () => {
    if (version != null && color != null) {
      const versionLabel =
        car.versions?.find((x) => x.id === version)?.title ||
        car.versions?.find((x) => x.id === version)?.titile ||
        '';
      const colorLabel = car.colors?.find((c) => c.id === color)?.name || '';
      const payload = {
        car_id: car.id,
        version_id: version,
        color_id: color,
        addon_ids: selectedAddonIds.map((id) => Number(id)),
        name: car.name,
        version: versionLabel,
        color: colorLabel,
        addons: selectedAddons.map((a) => ({
          id: a.id,
          title: a.title,
          price: a.price ?? 0,
        })),
        price: totalPrice,
      };
      setSelectedCar(payload);
      onClose();
    }
  };

  return (
    <div className="d-flex flex-column gap-2">
      <div className="d-flex flex-column gap-2">
        <span className="car-customization-label">Wersja</span>
        <div className="version-group">
          {car.versions?.map((v) => (
            <button
              key={v.id}
              type="button"
              className={`version-btn ${version === v.id ? 'active' : ''}`}
              onClick={() => setVersion(v.id)}
            >
              {v.title || v.titile || v.name}
            </button>
          ))}
        </div>
      </div>

      <div className="d-flex flex-column gap-2">
        <span className="car-customization-label">Kolor</span>
        <div className="color-swatches">
          {car.colors?.map((c) => (
            <label key={c.id} className={`color-swatch ${color === c.id ? 'checked' : ''}`}>
              <input
                type="radio"
                name="color"
                checked={color === c.id}
                onChange={() => setColor(c.id)}
                style={{ display: 'none' }}
              />
              <span
                className="color-dot"
                style={{
                  backgroundColor: c.value,
                  border: `1px solid ${c.value}`,
                }}
              />
            </label>
          ))}
        </div>
      </div>

      <div className="d-flex flex-column gap-2">
        <span className="car-customization-label">Dodatki</span>
        <div className="addon-group">
          {car.additionals?.map((a) => (
            <button
              key={a.id}
              type="button"
              className={`addon-btn ${selectedAddonIds.includes(a.id) ? 'active' : ''}`}
              onClick={() => toggleAddon(a.id)}
            >
              {a.title}
            </button>
          ))}
        </div>
      </div>

      <div className="d-flex flex-column gap-2">
        <div className="d-flex flex-column">
          <span className="car-customization-label">Cena</span>
          <span className="fw-bold fs-4" style={{ color: 'var(--navy)' }}>
            {formatPrice(totalPrice)} zł
          </span>
        </div>

        <ButtonComponent
          title="Wybierz"
          width="100%"
          backgroundColor="var(--pink)"
          backgroundColorHover="var(--dark-pink)"
          height="40px"
          onClick={saveToSummary}
        />
      </div>
    </div>
  );
};

export default CarCustomization;

// src/components/CarRange/CarCustomization.vue
<script setup>
import { ref, computed } from "vue";
import ButtonComponent from "../common/ButtonComponent.vue";

const props = defineProps({
  car: {
    type: Object,
    required: true,
  },
});
const version = ref(
  props.car.selectedVersion ?? props.car.versions?.[0]?.title ?? ""
);
const basePrice = computed(() => {
  const v = props.car.versions?.find((x) => x.title === version.value);
  return v?.price ?? 0;
});
const selectedAddonTitles = ref([]);
const selectedAddons = computed(
  () =>
    props.car.additional?.filter((a) =>
      selectedAddonTitles.value.includes(a.title)
    ) ?? []
);
const addonsTotal = computed(() =>
  selectedAddons.value.reduce((sum, a) => sum + (a.price ?? 0), 0)
);
const totalPrice = computed(() => basePrice.value + addonsTotal.value);
const color = ref(props.car.colors?.[0] ?? "");

const formatPrice = (value) => value.toLocaleString("pl-PL");
const savetoLocalStorage = () => {
  const payload = {
    name: props.car.name,
    version: version.value,
    color: color.value,
    addons: selectedAddons.value,
    price: totalPrice.value,
  };
  localStorage.setItem("selectedCar", JSON.stringify(payload));
};
defineExpose({ open, close, savetoLocalStorage });
</script>

<template>
  <div class="d-flex flex-column gap-2">
    <div class="d-flex flex-column gap-2">
      <span class="car-customization-label">Wersja</span>
      <el-radio-group
        v-model="version"
        class="version-group"
      >
        <el-radio-button
          v-for="v in props.car.versions"
          :key="v.title"
          :label="v.title"
        >
          {{ v.title }}
        </el-radio-button>
      </el-radio-group>
    </div>
    <div class="d-flex flex-column gap-2">
      <span class="car-customization-label">Kolor</span>
      <el-radio-group
        v-model="color"
        class="color-swatches"
      >
        <el-radio
          v-for="c in props.car.colors"
          :key="c"
          :label="c"
          class="color-swatch"
        >
          <span
            class="color-dot"
            :style="{
              backgroundColor: c,
              border: `1px solid ${c}`,
            }"
          />
        </el-radio>
      </el-radio-group>
    </div>
    <div class="d-flex flex-column gap-2">
      <span class="car-customization-label">Dodatki</span>
      <el-checkbox-group
        v-model="selectedAddonTitles"
        class="addon-group"
      >
        <el-checkbox-button
          v-for="a in props.car.additional"
          :key="a.title"
          :label="a.title"
        >
          {{ a.title }}
        </el-checkbox-button>
      </el-checkbox-group>
    </div>
    <div class="d-flex flex-column gap-2">
      <div class="d-flex flex-column">
        <span class="car-customization-label">Cena</span>
        <span
          class="fw-bold fs-4"
          style="color: var(--navy)"
        >
          {{ formatPrice(totalPrice) }} zł
        </span>
      </div>

      <ButtonComponent
        title="Znajdź punkt sprzedaży"
        class="w-100 mt-2"
        background-color="var(--green)"
        background-color-hover="var(--dark-green)"
        height="40px"
        @handle-click="savetoLocalStorage"
      />
    </div>
  </div>
</template>
<style>
.el-radio-group {
  display: flex;
  gap: 8px;
}
.car-customization-label {
  color: var(--dark-grey);
  font-size: var(--fs-s);
}
.el-radio-group .el-radio-button__inner {
  height: 32px;
  font-size: var(--fs-xs);
  color: var(--navy);
  background: #fff;
  border: 1px solid var(--grey) !important;
  border-radius: 8px !important;
  font-weight: 400;
}
.el-radio-button.is-active
  .el-radio-button__original-radio:not(:disabled)
  + .el-radio-button__inner {
  background-color: var(--main-color);
  border: 1px solid var(--main-color) !important;
  font-weight: 700;
}
.el-checkbox-button .el-checkbox-button__inner {
  height: 32px;
  font-size: var(--fs-xs);
  color: var(--navy);
  background: #fff;
  border: 1px solid var(--grey) !important;
  border-radius: 8px !important;
  width: 100%;
}
.el-checkbox-button.is-checked .el-checkbox-button__inner {
  background: var(--main-color);
  border: 1px solid var(--main-color) !important;;
  font-weight: 700;
}
.color-dot {
  display: inline-block;
  width: 28px;
  height: 28px;
  border-radius: 8px;
}
.color-swatches .el-radio {
  margin: 0;
}
.color-swatches .el-radio__inner {
  display: none;
}
.color-swatches .el-radio__input {
  margin-right: 0 !important;
}
.color-swatches .el-radio__label {
  padding-left: 0 !important;
}
.color-swatch:focus-within .color-dot,
.color-swatch.is-checked .color-dot {
  box-shadow: 3px 3px 3px var(--dark-grey);
  outline-offset: 2px;
  border-radius: 8px;
}
.version-group,
.addon-group {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 8px;
  width: 100%;
}

.version-group .el-radio-button,
.addon-group .el-radio-button {
  width: 100%;
}

.version-group .el-radio-button__inner,
.addon-group .el-radio-button__inner {
  width: 100%;
}
.version-group {
  grid-template-columns: repeat(3, 1fr);
}
</style>
