// platform-react/src/components/CarRange/CarModal.tsx
import React, { useImperativeHandle, forwardRef } from 'react';
import Modal from '../common/Modal';
import SectionCard from '../common/SectionCard';
import CarGallery from './CarGallery';
import CarCustomization from './CarCustomization';
import CarFeatures from './CarFeatures';
import './CarGallery.css';
import './CarModal.css';
import type { Car } from '../../types';

interface CarModalProps {
  car: Car;
}

export interface CarModalRef {
  open: () => void;
  close: () => void;
}

const CarModal = forwardRef<CarModalRef, CarModalProps>(({ car }, ref) => {
  const [isDialogOpen, setIsDialogOpen] = React.useState(false);

  const open = () => setIsDialogOpen(true);
  const close = () => setIsDialogOpen(false);

  useImperativeHandle(ref, () => ({
    open,
    close,
  }));

  return (
    <Modal isOpen={isDialogOpen} onClose={close} title={car.name ?? ''}>
      <div className="car-modal">
        <div className="car-gallery">
          <CarGallery images={car.images ?? []} />
        </div>
        <div className="d-flex flex-column gap-3">
          <SectionCard padding="16px 14px">
            <CarCustomization car={car} onClose={close} />
          </SectionCard>
          <SectionCard padding="16px 14px">
            <CarFeatures
              acceleration={car.acceleration_0_100_s || '0'}
              max_speed={car.max_speed_kmh || '0'}
              charging={car.charging || '0'}
              trunk_capacity={car.trunk_capacity || '0'}
              guarantee={car.guarantee || '0'}
            />
          </SectionCard>
        </div>
      </div>
    </Modal>
  );
});

CarModal.displayName = 'CarModal';

export default CarModal;

// src/components/CarRange/CarModal.vue
<script setup>
import { ref } from "vue";
import ButtonComponent from "../common/ButtonComponent.vue";
import SectionCard from "../common/SectionCard.vue";
import Modal from "../common/Modal.vue";
import CarCustomization from "./CarCustomization.vue";
import CarGallery from "./CarGallery.vue";
import CarFeatures from "./CarFeatures.vue";

const props = defineProps({
  car: {
    type: Object,
    required: true,
  },
});

const isDialogOpen = ref(false);

const open = () => (isDialogOpen.value = true);
const close = () => (isDialogOpen.value = false);
defineExpose({ open, close });
</script>
<template>
  <Modal
    v-model:is-open="isDialogOpen"
    :header="car.name"
  >
    <template #content>
      <div class="car-modal">
        <div class="car-gallery"><CarGallery :images="car.images" /></div>
        <div class="d-flex flex-column gap-3">
          <SectionCard padding="16px 14px">
            <template #content>
              <CarCustomization :car="car" />
            </template>
          </SectionCard>
          <SectionCard padding="16px 14px">
            <template #content>
              <CarFeatures
                :acceleration="car.acceleration_0_100_s"
                :max_speed="car.max_speed_kmh"
                :charging="car.charging"
                :trunk_capacity="car.trunk_capacity"
                :guarantee="car.guarantee"
              />
            </template>
          </SectionCard>
        </div>
      </div>
    </template>
    <template #footer>
      <ButtonComponent
        title="Anuluj"
        width="100px"
        background-color="#fff"
        color="var(--navy)"
        @handle-click="close"
        :font-weight="400"
        border="1px solid var(--grey)"
      />
      <ButtonComponent
        title="Znajdź dealera"
        width="134px"
      />
    </template>
  </Modal>
</template>
<style scoped>
.car-modal {
  display: flex;
  gap: 36px;
}
.car-gallery {
  width: 660px;
}
@media (max-width: 1200px) {
  .car-modal {
    flex-direction: column;
  }
  .car-gallery {
    width: 100%;
  }
}
</style>
