// platform-react/src/components/CarRange/CarSearchEngine.tsx
import React, { useState } from 'react';
import SectionCard from '../common/SectionCard';
import ButtonComponent from '../common/ButtonComponent';
import type { TypeItem, DriveItem } from '../../types';

interface CarSearchEngineProps {
  typesList: TypeItem[] | null;
  drivesList: DriveItem[] | null;
  isLoadingTypes: boolean;
  isLoadingDrives: boolean;
  onFilter: (filters: {
    type: string;
    drive: string;
    priceMin: number | null;
    priceMax: number | null;
  }) => void;
}

const CarSearchEngine: React.FC<CarSearchEngineProps> = ({
  typesList,
  drivesList,
  isLoadingTypes,
  isLoadingDrives,
  onFilter,
}) => {
  const [chosenType, setChosenType] = useState<string>('');
  const [chosenDrive, setChosenDrive] = useState<string>('');
  const [priceMin, setPriceMin] = useState<number | null>(null);
  const [priceMax, setPriceMax] = useState<number | null>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onFilter({
      type: chosenType,
      drive: chosenDrive,
      priceMin,
      priceMax,
    });
  };

  const handleNumberInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    e.target.value = e.target.value.replace(/\D+/g, '');
  };

  return (
    <SectionCard>
      <form
        onSubmit={handleSubmit}
        className="filters-form d-flex justify-content-between align-items-center w-100"
        style={{ gap: '16px' }}
      >
        <div className="filters row g-3 align-items-center flex-nowrap">
          <div className="field col-auto d-flex align-items-center gap-2">
            <label className="label m-0">Typ</label>
            <select
              className="form-select car-select"
              value={chosenType}
              onChange={(e) => setChosenType(e.target.value)}
              disabled={isLoadingTypes}
              style={{ width: '160px', height: '36px' }}
            >
              <option value="">Wybierz</option>
              {typesList?.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name}
                </option>
              ))}
            </select>
          </div>

          <div className="field col-auto d-flex align-items-center gap-2">
            <label className="label m-0">Napęd</label>
            <select
              className="form-select car-select"
              value={chosenDrive}
              onChange={(e) => setChosenDrive(e.target.value)}
              disabled={isLoadingDrives}
              style={{ width: '160px', height: '36px' }}
            >
              <option value="">Wybierz</option>
              {drivesList?.map((d) => (
                <option key={d.id} value={d.id}>
                  {d.name}
                </option>
              ))}
            </select>
          </div>

          <div className="field price col-auto d-flex align-items-center gap-2">
            <label className="label m-0">Cena</label>
            <div className="range-group d-inline-flex align-items-center gap-2">
              <input
                type="number"
                className="input"
                placeholder="min"
                value={priceMin || ''}
                onChange={(e) =>
                  setPriceMin(e.target.value ? Number(e.target.value) : null)
                }
                onInput={handleNumberInput}
              />
              <span className="dash">-</span>
              <input
                type="number"
                className="input"
                placeholder="max"
                value={priceMax || ''}
                onChange={(e) =>
                  setPriceMax(e.target.value ? Number(e.target.value) : null)
                }
                onInput={handleNumberInput}
              />
            </div>
          </div>
        </div>

        <div className="btn-wrap me-3">
          <ButtonComponent
            type="submit"
            title="Filtruj"
            width="135px"
            backgroundColor="var(--pink)"
            backgroundColorHover="var(--dark-pink)"
          />
        </div>
      </form>
    </SectionCard>
  );
};

export default CarSearchEngine;

// src/components/CarRange/CarSearchEngine.vue
<script setup>
import { ref } from "vue";
import SectionCard from "../common/SectionCard.vue";
import ButtonComponent from "../common/ButtonComponent.vue";

const types = ["SUV", "Kombi", "opcja3"];
const drives = ["Elektryczny", "Hybrydowy"];

const chosenType = ref("");
const chosenDrive = ref("");
const priceMin = ref(null);
const priceMax = ref(null);

const emit = defineEmits(["filter"]);

function onSubmit(e) {
  e?.preventDefault?.();
  emit("filter", {
    type: chosenType.value,
    drive: chosenDrive.value,
    priceMin: priceMin.value,
    priceMax: priceMax.value,
  });
}
</script>

<template>
  <SectionCard>
    <template #content>
      <form
        @submit="onSubmit"
        class="filters-form d-flex justify-content-between align-items-center w-100"
        style="gap: 16px"
      >
        <div class="filters row g-3 align-items-center flex-nowrap">
          <div class="field col-auto d-flex align-items-center gap-2-5">
            <label class="label m-0">Typ</label>

            <el-select
              v-model="chosenType"
              clearable
              placeholder="Wybierz"
              style="width: 160px; height: 36px"
              popper-class="select-popper"
            >
              <el-option
                v-for="t in types"
                :key="t"
                :label="t"
                :value="t"
              />
            </el-select>
          </div>

          <div class="field col-auto d-flex align-items-center gap-2-5">
            <label class="label m-0">Napęd</label>

            <el-select
              v-model="chosenDrive"
              placeholder="Wybierz"
              style="width: 160px; height: 36px"
              popper-class="select-popper"
              clearable
            >
              <el-option
                v-for="t in drives"
                :key="t"
                :label="t"
                :value="t"
              />
            </el-select>
          </div>

          <div class="field price col-auto d-flex align-items-center gap-2">
            <label class="label m-0">Cena</label>
            <div class="range-group d-inline-flex align-items-center gap-2">
              <input
                type="number"
                class="input"
                placeholder="min"
                clearable
                v-model.number="priceMin"
                @input="
                  $event.target.value = $event.target.value.replace(/\D+/g, '')
                "
              />
              <span class="dash">-</span>
              <input
                type="number"
                class="input"
                placeholder="max"
                clearable
                v-model.number="priceMax"
                @input="
                  $event.target.value = $event.target.value.replace(/\D+/g, '')
                "
              />
            </div>
          </div>
        </div>

        <div class="btn-wrap">
          <ButtonComponent
            @handle-click="onSubmit"
            title="Filtruj"
            class="me-3"
            width="135px"
            background-color="var(--pink)"
            background-color-hover="var(--dark-pink)"
          />
        </div>
      </form>
    </template>
  </SectionCard>
</template>

<style>
.SectionCard {
  height: 72px;
  display: flex;
  justify-content: center;
}
.filters.row {
  --bs-gutter-x: 20px !important;
}
.label {
  font-size: var(--fs-s);
  color: var(--dark-grey);
  white-space: nowrap;
}
.el-select {
  width: 160px;
  font-size: var(--fs-s);
  color: var(--navy);
}
.el-select__wrapper {
  border-radius: 8px !important;
  box-shadow: none;
  border: 1px solid var(--grey);
  color: var(--navy) !important;
  height: 36px;
  padding: 0 12px;
}
.el-select__wrapper.is-focused {
  box-shadow: none;
}
.el-select__wrapper.is-hovering:not(.is-focused) {
  box-shadow: none;
}
.el-select__placeholder {
  color: var(--navy) !important;
}
.el-select__placeholder.is-transparent {
  color: var(--navy) !important;
}
.range-group {
  border-radius: 8px;
}
.input {
  height: 36px;
  width: 81px;
  padding: 0 10px;
  border: 1px solid var(--grey);
  border-radius: 8px;
  background-clip: padding-box;
  font-size: var(--fs-s);
  color: var(--navy);
  transition: border-color 120ms ease;
}
.input:focus {
  outline: none;
  box-shadow: none;
}
input::placeholder {
  color: var(--navy);
}
.dash {
  color: var(--dark-grey);
  padding: 0 2px;
  font-size: var(--fs-s);
}

.input[type="number"]::-webkit-outer-spin-button,
.input[type="number"]::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
.input[type="number"] {
  -moz-appearance: textfield;
  appearance: textfield;
}
@media (max-width: 1000px) {
  .SectionCard {
    height: 100%;
  }
  .filters-form {
    flex-direction: column;
    align-items: stretch;
    gap: 12px;
  }
  .filters {
    flex-wrap: wrap !important;
  }
  .field {
    width: 100%;
  }
  .el-select {
    width: 100% !important;
  }
  .range-group {
    width: 100%;
  }
  .input {
    width: 100%;
  }
  .btn-wrap {
    width: 100%;
  }
  .btn-wrap > * {
    width: 100% !important;
  }
  .label {
    width: 60px;
  }
}
</style>
