// platform-react/src/components/Steps/StepOne.tsx
import React from "react";
import IntroComponent from "../MainPageComponents/IntroComponent";
import CarRanges from "../CarRange/CarRanges";
import InfoComponent from "../InfoComponent/InfoComponent";
import PromoBanner from "../PromoBanner";
import OutroComponent from "../OutroComponent";

const StepOne: React.FC = () => {
  return (
    <div className="app-container mx-auto d-flex flex-column gap-4 gap-md-5">
      <IntroComponent />

      <CarRanges />

      <PromoBanner />

      <InfoComponent />

      <OutroComponent />
    </div>
  );
};

export default StepOne;

// src/components/Steps/StepOne.vue
<script setup>
import IntroComponent from "../MainPageComponents/IntroComponent.vue";
import CarRanges from "../CarRange/CarRanges.vue";
import PromoBanner from "../PromoBanner.vue";
import InfoComponent from "../InfoComponent/InfoComponent.vue";
import OutroComponent from "../OutroComponent.vue";
</script>
<template>
  <div class="app-container mx-auto d-flex flex-column gap-4 gap-md-5">
    <IntroComponent />
    <CarRanges />
    <PromoBanner />
    <InfoComponent />
    <OutroComponent />
  </div>
</template>
