// platform-react/src/components/Footer.tsx
import React from 'react';
import TheSeparator from './common/TheSeparator';
import './Footer.css';

const Footer: React.FC = () => {
  return (
    <footer className="footer">
      <TheSeparator />
      <div className="container-fluid px-3">
        <div className="footer-content">
          <span className="footer-text">© 2025 Aureon Motors</span>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/Footer.vue
<script setup>
import TheSeparator from "./common/TheSeparator.vue";
</script>
<template>
  <footer class="bg-white">
    <TheSeparator />
    <div class="container-fluid px-3">
      <div
        class="container-fluid d-flex align-items-center justify-content-start mx-auto px-0"
        style="max-width: var(--app-width); height: 80px"
      >
        <span style="color: var(--dark-grey); font-size: var(--fs-s)"
          >© 2025 Voltura Motors</span
        >
      </div>
    </div>
  </footer>
</template>
<style scoped></style>
