// platform-react/src/components/common/ButtonComponent.tsx
import React, { useState } from 'react';
import './ButtonComponent.css';

interface ButtonComponentProps {
  title: string;
  onClick?: () => void;
  backgroundColor?: string;
  backgroundColorHover?: string;
  color?: string;
  colorHover?: string;
  width?: string;
  height?: string;
  fontSize?: string;
  fontWeight?: number;
  border?: string;
  borderHover?: string;
  type?: 'button' | 'submit' | 'reset';
}

const ButtonComponent: React.FC<ButtonComponentProps> = ({
  title,
  onClick,
  backgroundColor = 'var(--main-color)',
  backgroundColorHover = 'var(--dark-pink)',
  color = '#FFFFFF',
  colorHover = '#FFFFFF',
  width = '195px',
  height = '44px',
  fontSize = 'var(--fs-xs)',
  fontWeight = 700,
  border = 'none',
  borderHover = 'none',
  type = 'button',
}) => {
  const [isHover, setIsHover] = useState(false);

  return (
    <button
      type={type}
      className="button-component"
      style={{
        background: isHover ? backgroundColorHover : backgroundColor,
        color: isHover ? colorHover : color,
        width,
        height,
        fontSize,
        fontWeight,
        border: isHover ? borderHover : border,
      }}
      onMouseOver={() => setIsHover(true)}
      onMouseLeave={() => setIsHover(false)}
      onClick={onClick}
    >
      {title}
    </button>
  );
};

export default ButtonComponent;

// src/components/common/ButtonComponent.vue
<script setup>
import { ref } from "vue";
const emit = defineEmits(["handleClick"]);
const props = defineProps({
  title: {
    type: String,
    required: true,
  },
  backgroundColor: {
    type: String,
    default: "var(--main-color)",
  },
  backgroundColorHover: {
    type: String,
    default: "var(--main-hover-color)",
  },
  color: {
    type: String,
    default: "#FFFFFF",
  },
  colorHover: {
    type: String,
    default: "#FFFFFF",
  },
  width: {
    type: String,
    default: "195px",
  },
  height: {
    type: String,
    default: "44px",
  },
  fontSize: {
    type: String,
    default: "var(--fs-xs)",
  },
  fontWeight: {
    type: Number,
    default: 700,
  },
  border: {
    type: String,
    default: "none",
  },
  borderHover: {
    type: String,
    default: "none",
  },
});
const isHover = ref(false);
</script>
<template>
  <el-button
    class="button-component"
    :style="{
      background: isHover ? backgroundColorHover : backgroundColor,
      color: isHover ? colorHover : color,
      width: width,
      height: height,
      fontSize: fontSize,
      fontWeight: fontWeight,
      border: isHover ? borderHover : border,
    }"
    @mouseover="isHover = true"
    @mouseleave="isHover = false"
    @click="emit('handleClick')"
    >{{ title }}</el-button
  >
</template>
<style scoped>
.button-component {
  border: none;
  border-radius: 12px;
  transition: all 0.3s ease;
}
</style>
